//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Answers
    {
        public string login
        {
            get
            {
                var users = App.Context.Users.ToList();
                var user = users.Where(u => u.user_id == user_id).FirstOrDefault();
                return user.login;
            }
        }
        public string description
        {
            get
            {
                var tasks = App.Context.Tasks.ToList();
                var task = tasks.Where(t => t.task_id == task_id).FirstOrDefault();
                return task.description;
            }
        }
        public string subjectName
        {
            get
            {
                var tasks = App.Context.Tasks.ToList();
                var task = tasks.Where(t => t.task_id == task_id).FirstOrDefault();
                return task.subjectName;
            }
        }
        public string shortDate
        {
            get
            {
                return date.ToString("D");
            }
        }
        public string shortDescription
        {
            get
            {
                var task = App.Context.Tasks.Where(t => t.task_id == task_id).FirstOrDefault();
                var tsd = task.description.Substring(0, Math.Min(task.description.Length, 100));
                if (tsd != task.description)
                {
                    tsd += "...";
                }
                return tsd;
            }
        }
        public string shortCode
        {
            get
            {
                var sc = code.Replace("using System;\n\npublic class CourseWork\n{\n\tpublic static void Main(string[] args)\n\t{\n\t\t", "");
                sc = sc.Replace("\t", "");
                sc = sc.Substring(0, Math.Min(code.Length, 100));
                if (sc != code)
                {
                    sc += "...";
                }
                return sc;
            }
        }
        public int answer_id { get; set; }
        public int user_id { get; set; }
        public int task_id { get; set; }
        public string code { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
    }
}
