//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id_history { get; set; }
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
        public string Day
        {
            get
            {
                return date.ToString("D");
            }
        }
        public string time
        {
            get
            {
                return date.ToString("t");
            }
        }

        public virtual Users Users { get; set; }
    }
}
