//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        public int test_id { get; set; }
        public int task_id { get; set; }
        public string input { get; set; }
        public string output { get; set; }
    
        public virtual Tasks Tasks { get; set; }
    }
}
